# ECR_URL ENV 추가
version: 0.2

phases:
  pre_build:
    commands:
      - sudo rm -rf /etc/localtime
      - sudo ln -s /usr/share/zoneinfo/Asia/Seoul /etc/localtime
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URL
      - export TAG="$(date '+%Y-%m-%d.%H.%M.%S')"
  build:
    commands:
      - docker build -t temp .
  post_build:
    commands:
      - docker tag temp:latest $ECR_URL:$TAG
      - docker push $ECR_URL:$TAG