config:
  argocd:
    grpcWeb: true
    serverAddress: "http://argocd-server.argocd"
    insecure: true
    plaintext: true
  registries:
    - name: ECR
      api_url: https://972209100553.dkr.ecr.us-east-1.amazonaws.com/stress
      prefix: 972209100553.dkr.ecr.us-east-1.amazonaws.com/stress
      ping: true
      insecure: false
      credentials: "ext:/scripts/auth.sh"
      credsexpire: 10h
authScripts:
  enabled: true
  scripts:
    auth.sh: |
      #!/bin/sh
      aws ecr --region us-east-1 get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d
